diff --git a/Makefile b/Makefile
index f68eff9..15c34ff 100644
--- a/Makefile
+++ b/Makefile
@@ -8,7 +8,7 @@ INC_DIR := include
 VERBOSE := 0
 LIBS := xcb-atom
 
-PREFIX := /usr/local
+PREFIX := $(HOME)/.local
 CFLAGS := -Ofast -I. -I$(INC_DIR) -std=c99
 CFLAGS += -DBINARY=\"$(BIN)\" -D_POSIX_C_SOURCE=200809L
 CFLAGS += -Wall -Wpedantic -Wextra -Wswitch-enum
