#!/bin/sh

read file
rfile=`realpath "$file"`

case "$1" in

"Escape")   exit 1 ;;

"C-d")	    rm "$rfile" ;;

"C-g")	    gimp "$rfile" & ;;

"C-j")	    mogrify -format jpg "$rfile" ;;

# when height is more
"C-c")	    convert "$rfile" -scale 1920x "$rfile" && \
	    aspectcrop -a 16:9 "$rfile" "$rfile" ;;

# when width is more
"C-v")	    convert "$rfile" -scale x1080 "$rfile" && \
	    aspectcrop -a 16:9 "$rfile" "$rfile" ;;

"C-w")	    jpg2ff < "$rfile" \
            > ~/.cache/st_bg.ff; \
	    say refstbg; \
	    pidof st | xargs kill -s USR1 ;;

esac
