diff --git a/Makefile b/Makefile
index 2db479f..dee8425 100644
--- a/Makefile
+++ b/Makefile
@@ -6,6 +6,7 @@ include config.mk
 SRC = tabbed.c xembed.c
 OBJ = ${SRC:.c=.o}
 BIN = ${OBJ:.o=}
+PREFIX = $(HOME)/.local
 
 all: options ${BIN}
 
